export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_OUT = 'SIGNED_OUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_REQUEST = "POST_REQUEST";
export const POST_FAIL = "POST_FAIL";

export const CONTEST_REGISTER_REQUEST = "CONTEST_REGISTER_REQUEST";
export const CONTEST_REGISTER_SUCCESS = "CONTEST_REGISTER_SUCCESS";
export const CONTEST_REGISTER_FAIL = "CONTEST_REGISTER_FAIL";


export const DISPLAY_CONTEST_REGISTER_REQUEST = "DISPLAY_CONTEST_REGISTER_REQUEST";
export const DISPLAY_CONTEST_REGISTER_SUCCESS = "DISPLAY_CONTEST_REGISTER_SUCCESS";
export const DISPLAY_CONTEST_REGISTER_FAIL = "DISPLAY_CONTEST_REGISTER_FAIL";

export const CONTY_REGISTER_REQUEST = "CONTY_REGISTER_REQUEST";
export const CONTY_REGISTER_SUCCESS = "CONTY_REGISTER_SUCCESS";
export const CONTY_REGISTER_FAIL = "CONTY_REGISTER_FAIL";

export const SET_PRICE_REQUEST = "SET_PRICE_REQUEST";
export const SET_PRICE_SUCCESS = "SET_PRICE_SUCCESS";
export const SET_PRICE_FAIL = "SET_PRICE_FAIL";